apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: inventorymanagement
  name: inventorymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventorymanagement
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
       
      labels:
        io.kompose.service: inventorymanagement
    spec:
      containers:
        - image: soa-project-inventorymanagement
          name: inventorymanagement
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
